<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit();
}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_614eda154e2ed',
	'title' => 'Detalhes do Formulário',
	'fields' => array(
		array(
			'key' => 'field_614edb33cff72',
			'label' => 'Adicionar Serviços',
			'name' => 'form_services',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_614edbc256529',
					'label' => 'Nome do serviços',
					'name' => 'services_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Nome do Serviço',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_614ee0904a975',
					'label' => 'Título do serviços',
					'name' => 'services_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Serviços/Produtos',
					'placeholder' => 'Digite o título do serviço \'.\'',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_614f677241205',
					'label' => 'Unidade de Medida',
					'name' => 'services_measurement',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'M²' => 'M²',
						'Metro linear' => 'Metro linear',
						'Unidade' => 'Unidade',
						'Peça' => 'Peça',
						'Kilo' => 'Kilo',
						'Litro' => 'Litro',
						'Galão' => 'Galão',
						'Lata' => 'Lata',
						'Tonelada' => 'Tonelada',
						'Saco' => 'Saco',
						'Serviço' => 'Serviço',
						'Execução' => 'Execução',
						'Hora' => 'Hora',
						'Dia' => 'Dia',
						'Mês' => 'Mês',
						'Km' => 'Km',
					),
					'default_value' => 'M²',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_614ee0904a775',
					'label' => 'Preço por Medição',
					'name' => 'services_price',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => '0.00',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_614ee0b04a775',
					'label' => 'Taxa Saída',
					'name' => 'services_exit_fee',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => '0.00',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_614e7g904a775',
					'label' => 'Valor Fixo',
					'name' => 'services_fixed_price',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => '0.00',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_614f688ef4650',
			'label' => 'Adicionar Postos',
			'name' => 'form_works',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_614f688ef4651',
					'label' => 'Função',
					'name' => 'works_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Nome do Posto',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_614ee0904a475',
					'label' => 'Título de Função',
					'name' => 'works_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Postos',
					'placeholder' => 'Digite o título do Postos \'.\'',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),				
				array(
					'key' => 'field_614f677f41205',
					'label' => 'Unidade de Medida',
					'name' => 'works_measurement',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'M²' => 'M²',
						'Metro linear' => 'Metro linear',
						'Unidade' => 'Unidade',
						'Peça' => 'Peça',
						'Kilo' => 'Kilo',
						'Litro' => 'Litro',
						'Galão' => 'Galão',
						'Lata' => 'Lata',
						'Tonelada' => 'Tonelada',
						'Saco' => 'Saco',
						'Serviço' => 'Serviço',
						'Execução' => 'Execução',
						'Hora' => 'Hora',
						'Dia' => 'Dia',
						'Mês' => 'Mês',
						'Km' => 'Km',
					),
					'default_value' => 'M²',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_614f688ef4653',
					'label' => 'Preço/Hora',
					'name' => 'works_price',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => '0.00',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_614f6b8ef4653',
					'label' => 'Taxa Saída',
					'name' => 'works_exit_fee',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => '0.00',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_614f6g8ef4653',
					'label' => 'Valor Fixo',
					'name' => 'works_fixed_price',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => '0.00',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				/*array(
					'key' => 'field_614f688ef4652',
					'label' => 'Adic. Noturno',
					'name' => 'works_additional',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => 'Somente número e ponto \'.\'',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),*/
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'budget',
			),
			array(
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'administrator',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

endif;		